services:
  api:
    build: .
    container_name: blog-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      # Add dependency on Redis
      redis:
        condition: service_started # Or service_healthy if using a healthcheck for redis
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=yourpassword
      - DB_DATABASE=blogdb
      - JWT_SECRET=Hoss@Home#01120399909
      - HASH_ROUNDS=10
      - ADMIN_FIRST_NAME=Admin
      - ADMIN_LAST_NAME=User
      - ADMIN_EMAIL=admin@blog.com
      - ADMIN_PASSWORD=admin123
      - ADMIN_PHONE=+1234567890
      # Add Redis connection details
      - REDIS_HOST=redis # Use the service name defined below
      - REDIS_PORT=6379 # Default Redis port
      # i will debend on that later for SSl
      - NODE_ENV=development

    volumes:
      - ./src:/app/src
      # - ./ssl:/app/ssl  # volume for SSL certificates
    command: sh -c "sleep 5 && npm run migration:run && npm run start:dev"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:15-alpine
    container_name: blog-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=blogdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: blog-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
