[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker buildx build --platform linux/amd64 -t 1hoss/blogy:latest ."

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
NODE_ENV = "production"
PORT = "3000"
JWT_SECRET = "Hoss@Home"